Assignment 4 - Linear Regression

Read all the instrutions carefully before answering each question.


Write your code to read the file named 'pubg_final.csv' uploaded in the blackboard. Read the file in the same format as given. Do not convert it into .xlsx or other formats. After reading the file write your code to show the top 5 rows in the dataset.

In [1]:
import pandas as pd
import seaborn as sns

# 1. Write code to read the data and display the first 5 lines here.
#student response
df = pd.read_csv("Pubg_Final.csv")
df.head()

,Assists,Boosts,Damagedealt,Headshotkills,Heals,Kills,Longestkill,Matchduration,Matchkillrank,Revives,Ridedistance,Swimdistance,Teamkills,Walkdistance,Weaponsacquired,Winplaceperc,Ln Damage Dealt,Ln Match Kill Rank,Ln Win Place Perc
0,0,0,53.32,0,0,0,0.000,1208.0,53,0,0.0,0.0,0,603.6,3,0.6354,3.976311,3.970292,-0.453501
1,1,3,427.50,0,1,3,181.800,1871.0,11,0,5479.0,0.0,0,2716.0,6,0.9615,6.057954,2.397895,-0.039261
2,0,3,393.10,1,5,3,29.670,1327.0,12,1,756.8,0.0,0,2107.0,3,0.8511,5.974064,2.484907,-0.161226
3,0,0,142.90,1,0,2,21.610,1921.0,25,0,0.0,0.0,0,161.3,2,0.0769,4.962145,3.218876,-2.565249
4,0,0,61.64,0,3,1,2.046,1873.0,28,0,0.0,0.0,1,455.8,4,0.3125,4.121311,3.332205,-1.163151

In [2]:
df.shape

(5000, 19)

In [3]:
# 2. Write code to show count of non-null data and column data types here.
#student response
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Assists             5000 non-null   int64
 1   Boosts              5000 non-null   int64
 2   Damagedealt         5000 non-null   float64
 3   Headshotkills       5000 non-null   int64
 4   Heals               5000 non-null   int64
 5   Kills               5000 non-null   int64
 6   Longestkill         5000 non-null   float64
 7   Matchduration       5000 non-null   float64
 8   Matchkillrank       5000 non-null   int64
 9   Revives             5000 non-null   int64
 10  Ridedistance        5000 non-null   float64
 11  Swimdistance        5000 non-null   float64
 12  Teamkills           5000 non-null   int64
 13  Walkdistance        5000 non-null   float64
 14  Weaponsacquired     5000 non-null   int64
 15  Winplaceperc        5000 non-null   float64
 16  Ln Damage Dealt     5000 non-null   float64
 17  Ln Match Kill Rank  5000 non-null   float64
 18  Ln Win Place Perc   5000 non-null   float64
dtypes: float64(10), int64(9)
memory usage: 742.3 KB

In [4]:
# 3. Provide the summary statistics of the dataset
#student response
df.describe()

,Assists,Boosts,Damagedealt,Headshotkills,Heals,Kills,Longestkill,Matchduration,Matchkillrank,Revives,Ridedistance,Swimdistance,Teamkills,Walkdistance,Weaponsacquired,Winplaceperc,Ln Damage Dealt,Ln Match Kill Rank,Ln Win Place Perc
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,0.326200,1.431200,185.315704,0.331200,1.794600,1.321400,32.499768,1575.916200,37.865600,0.216200,719.179654,4.662469,0.017400,1386.913008,4.136000,0.544779,4.803310,3.298700,-0.846153
std,0.688976,1.859021,181.526250,0.729392,3.044317,1.770404,57.374340,259.476332,24.936646,0.524893,1637.849895,29.445735,0.138207,1236.688793,2.388691,0.292414,0.986410,0.978038,0.822131
min,0.000000,0.000000,0.140000,0.000000,0.000000,0.000000,0.000000,352.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010200,-1.935861,0.000000,-4.585368
25%,0.000000,0.000000,70.730000,0.000000,0.000000,0.000000,0.000000,1365.000000,17.000000,0.000000,0.000000,0.000000,0.000000,276.200000,2.000000,0.296300,4.258870,2.833213,-1.216383
50%,0.000000,1.000000,125.800000,0.000000,1.000000,1.000000,7.688000,1436.000000,34.000000,0.000000,0.000000,0.000000,0.000000,1102.000000,4.000000,0.553200,4.834693,3.526361,-0.592036
75%,0.000000,2.000000,241.425000,0.000000,2.000000,2.000000,38.365000,1848.250000,56.000000,0.000000,412.250000,0.000000,0.000000,2277.250000,5.000000,0.807700,5.486558,4.025352,-0.213565
max,7.000000,13.000000,1812.000000,13.000000,44.000000,22.000000,545.500000,2198.000000,98.000000,5.000000,15900.000000,629.900000,2.000000,12220.000000,42.000000,1.000000,7.502186,4.584967,0.000000

#4. In your own words, what do you mean by correlation?
Ans:
Correlation refers to the association between two independent features.

In [ ]:
#5. Write code to calculate and show the correlation matrix for all integer and float values in the dataset.

#Student response

In [ ]:
# 6. Import the necessary library and display the heatmap for the correlation matrix
#student response

# 7. We will choose "Winplaceperc" as the target variable for most of the regressions in this homework..
Looking at the correlation table and heatmap, which other features are most strongly correlated with the Winplaceperc?

# 8. What is the purpose of the correlation table for a linear regression model?

In [ ]:
# 9. import necessary libraries and display the pairplot
#student response

In [ ]:
df.info()

In [ ]:
# 10. Take "Kills" as the response variable and "Ln Match Kill Rank" as the predictor. 
# Perform a simple linear regression.
import statsmodels.api as sm

#student response

In [ ]:
# 11. Show the plot for the above simple linear regression model.

import matplotlib.pyplot as plt

#student response

# 12. What do you mean by response variable and predictor variable?
#student response
'''The response variable, also known as the dependent variable, is the variable that you are trying to predict or 
explain in a linear regression model. It is the outcome or result that you are interested in understanding or 
modeling.
Predictor variables, also known as independent variables or features, are the variables that you believe have an 
influence or explanatory power on the response variable. These variables are used to make predictions about the 
response variable
'''

In [ ]:
# 13. Using 'Winplaceperc' as the response variable, perform a full linear regression model
import statsmodels.api as sm

#Student response

In [ ]:
# 14. Perform a 4-feature multiple linear regression using Winplaceperc as the response variable
# and "Kills", "Walk distance", "Matchkillrank", and "Boosts" as the predictors.

#Student response

# 15. Observe the outputs and mention the differences between the full and 4-feature multiple regression models. Which model do you prefer and why?

#Student response

# 16a. Write down the equation for the regression "line" (a.k.a. hyperplane, space) from the output of the 4-feature multiple linear regression. 

# 16b. Irrespective of the quality of the above obtained multiple linear regression model, 
and without using software, predict the winplaceperc for 
2.1 Boosts, 2012 walk distance, 21 Matchkillrank and 5 kills
#student response

# 17. What is the difference between R-squared and adjusted R-squared? 
Do we have same R-squared and adj. R-squared for simple linear regression? How do you explain that?'''
#student response

In [ ]:
# 18. Display the partial regression plots on the 4-feature multiple linear regression

#Student response

In [ ]:
# 19. Draw the Q-Q plot for the 4-feature multiple linear regression

#Student Response